# Discussion 2: Pandas Practice

This notebook contains all the same questions from the Discussion 2 worksheet. The following questions are based on the `elections.csv` data referenced in the lecture.

In [1]:
# import packages
import pandas as pd
import numpy as np
elections = pd.read_csv('elections.csv')
elections.head(10)

,Year,Candidate,Party,Popular vote,Result,%
0,1824,Andrew Jackson,Democratic-Republican,151271,loss,57.210122
1,1824,John Quincy Adams,Democratic-Republican,113142,win,42.789878
2,1828,Andrew Jackson,Democratic,642806,win,56.203927
3,1828,John Quincy Adams,National Republican,500897,loss,43.796073
4,1832,Andrew Jackson,Democratic,702735,win,54.574789
5,1832,Henry Clay,National Republican,484205,loss,37.603628
6,1832,William Wirt,Anti-Masonic,100715,loss,7.821583
7,1836,Hugh Lawson White,Whig,146109,loss,10.005985
8,1836,Martin Van Buren,Democratic,763291,win,52.272472
9,1836,William Henry Harrison,Whig,550816,loss,37.721543

## Problem 1
Write a line of code that returns the `elections` table sorted in descending order by `"Popular vote"`. Store your result in a variable named `sorted`. Would calling `sorted.iloc[[0], :]` give the same result as `sorted.loc[[0], :]`?

*Answer*:

In [3]:
sorted = elections.sort_values("Popular vote", ascending=False)

In [4]:
sorted.iloc[[0], :]

     Year     Candidate       Party  Popular vote Result          %
178  2020  Joseph Biden  Democratic      81268924    win  51.311515

In [5]:
sorted.loc[[0], :]

   Year       Candidate                  Party  Popular vote Result          %
0  1824  Andrew Jackson  Democratic-Republican        151271   loss  57.210122

## Problem 2

Using Boolean slicing, write one line of `pandas` code that returns a `DataFrame` that only contains election results from the 1900s.

*Answer*:

In [6]:
elections[elections['Year']==1900]

    Year               Candidate        Party  Popular vote Result          %
54  1900         John G. Woolley  Prohibition        210864   loss   1.526821
55  1900  William Jennings Bryan   Democratic       6370932   loss  46.130540
56  1900        William McKinley   Republican       7228864    win  52.342640

## Problem 3

Write one line of `pandas` code that returns a `Series`, where the index is the `"Party"`, 
and the values are how many times that party won an election. Only include parties that have won an election.

_Answer:_

In [20]:
elections[elections['Result'] == 'win'].groupby('Party').size()

Party
Democratic               23
Democratic-Republican     1
National Union            1
Republican               24
Whig                      2
dtype: int64

## Problem 4

Write a line of `pandas` code that returns a `Series` whose index is the years and whose values are the number of candidates that participated in those years' elections.

*Answer:*

In [26]:
elections.groupby('Year').size()

Year
1824    2
1828    2
1832    3
1836    3
1840    2
1844    2
1848    3
1852    3
1856    3
1860    4
1864    2
1868    2
1872    2
1876    2
1880    3
1884    4
1888    4
1892    4
1896    4
1900    3
1904    5
1908    4
1912    5
1916    4
1920    5
1924    3
1928    3
1932    4
1936    4
1940    3
1944    2
1948    6
1952    3
1956    3
1960    2
1964    2
1968    3
1972    3
1976    6
1980    5
1984    3
1988    4
1992    5
1996    7
2000    5
2004    6
2008    6
2012    4
2016    6
2020    4
2024    5
dtype: int64

## Problem 5

Write a line of `pandas` code that creates a filtered `DataFrame` named `filtered_parties`
from the elections dataset and keeps only the parties that have at least one election %
more than 50%.

*Answer*:

In [31]:
filtered_parties = elections.groupby('Party').filter(lambda c: np.any(c['%'] > 50))
filtered_parties

,Year,Candidate,Party,Popular vote,Result,%
0,1824,Andrew Jackson,Democratic-Republican,151271,loss,57.210122
1,1824,John Quincy Adams,Democratic-Republican,113142,win,42.789878
2,1828,Andrew Jackson,Democratic,642806,win,56.203927
4,1832,Andrew Jackson,Democratic,702735,win,54.574789
7,1836,Hugh Lawson White,Whig,146109,loss,10.005985
...,...,...,...,...,...,...
176,2016,Hillary Clinton,Democratic,65853514,loss,48.521539
178,2020,Joseph Biden,Democratic,81268924,win,51.311515
179,2020,Donald Trump,Republican,74216154,loss,46.858542
182,2024,Donald Trump,Republican,77303568,win,49.808629
183,2024,Kamala Harris,Democratic,75019230,loss,48.336772

## Problem 6

Write a line of `pandas` code that uses the `filtered_parties` `DataFrame` to return a new
`DataFrame` with row indices that correspond to the year and columns that correspond
to each party. Each entry should be the total percentage of votes for all the candidates
that ran during that particular year for the specified party. Missing values from the dataset (the cases where a party did not have a candidate in a particular year) should be entered as 0. Below is an example.

![](pivot.png)

In [38]:
filtered_parties.pivot_table(index='Year', columns='Party', values='%', aggfunc='sum', fill_value=0)

Party,Democratic,Democratic-Republican,National Union,Republican,Whig
Year,,,,,
1824,0.000000,100.0,0.000000,0.000000,0.000000
1828,56.203927,0.0,0.000000,0.000000,0.000000
1832,54.574789,0.0,0.000000,0.000000,0.000000
1836,52.272472,0.0,0.000000,0.000000,47.727528
1840,46.948787,0.0,0.000000,0.000000,53.051213
1844,50.749477,0.0,0.000000,0.000000,49.250523
1848,42.552229,0.0,0.000000,0.000000,47.309296
1852,51.013168,0.0,0.000000,0.000000,44.056548
1856,45.306080,0.0,0.000000,33.139919,0.000000
1860,0.000000,0.0,0.000000,39.699408,0.000000
1864,45.048488,0.0,54.951512,0.000000,0.000000
1868,47.334695,0.0,0.000000,52.665305,0.000000
1872,0.000000,0.0,0.000000,55.928594,0.000000
1876,51.528376,0.0,0.000000,48.471624,0.000000
1880,48.278422,0.0,0.000000,48.369234,0.000000
1884,48.884933,0.0,0.000000,48.312208,0.000000
1888,48.656799,0.0,0.000000,47.858041,0.000000
1892,46.121393,0.0,0.000000,42.984101,0.000000
1896,46.871053,0.0,0.000000,51.213817,0.000000
1900,46.130540,0.0,0.000000,52.342640,0.000000
1904,37.685116,0.0,0.000000,56.562787,0.000000
1908,43.414640,0.0,0.000000,52.013300,0.000000
1912,41.933422,0.0,0.000000,23.218466,0.000000
1916,49.367987,0.0,0.000000,46.240779,0.000000
1920,34.293063,0.0,0.000000,60.574501,0.000000
1924,28.976291,0.0,0.000000,54.329113,0.000000
1928,40.902853,0.0,0.000000,58.368524,0.000000
1932,57.672125,0.0,0.000000,39.830594,0.000000
1936,60.978107,0.0,0.000000,36.648285,0.000000
1940,54.871202,0.0,0.000000,44.894561,0.000000
1944,53.773801,0.0,0.000000,46.226199,0.000000
1948,49.601536,0.0,0.000000,45.112958,0.000000
1952,44.446312,0.0,0.000000,55.325173,0.000000
1956,42.174464,0.0,0.000000,57.650654,0.000000
1960,50.082561,0.0,0.000000,49.917439,0.000000
1964,61.344703,0.0,0.000000,38.655297,0.000000
1968,42.863537,0.0,0.000000,43.565246,0.000000
1972,37.670670,0.0,0.000000,60.907806,0.000000
1976,50.271900,0.0,0.000000,48.199499,0.000000
1980,41.132848,0.0,0.000000,50.897944,0.000000
1984,40.729429,0.0,0.000000,59.023326,0.000000
1988,45.770691,0.0,0.000000,53.518845,0.000000
1992,43.118485,0.0,0.000000,37.544784,0.000000
1996,49.296938,0.0,0.000000,40.766036,0.000000
2000,48.491813,0.0,0.000000,47.974666,0.000000
2004,48.306775,0.0,0.000000,50.771824,0.000000
2008,53.023510,0.0,0.000000,45.737243,0.000000
2012,51.258484,0.0,0.000000,47.384076,0.000000
2016,48.521539,0.0,0.000000,46.407862,0.000000
2020,51.311515,0.0,0.000000,46.858542,0.000000
2024,48.336772,0.0,0.000000,49.808629,0.000000